apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-private-cluster-pipeline 
description: main application pipeline
serialPipeline:
 stages:
 - targetId: my-private-cluster
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: my-private-cluster
description: private cluster
anthosCluster:
 membership: projects/gke-demo-347012/locations/australia-southeast1/memberships/autopilot-cluster-0	
executionConfigs:
- defaultPool:
    serviceAccount: connect-gw-sa@gke-demo-347012.iam.gserviceaccount.com
  usages:
    - RENDER
    - DEPLOY
