steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args: ['get', 'nodes']
  env:
  - "CLOUDSDK_COMPUTE_REGION=$LOCATION"
  - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/$PROJECT_ID/locations/$LOCATION/workerPools/private-pool'
