steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args: ['get', 'nodes']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-private'
options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/$PROJECT_ID/locations/$LOCATION/workerPools/private-pool'
